### ISSUE TITLE
Problema para abrir fallback

### ISSUE THREAD

**Issue by felipe-chamas** [guilhermeguldi/RA-Guldi#1]
https://github.com/guilhermeguldi/RA-Guldi/blob/740606f38494f129b28378026501e79a238bf539/script.js#L23

@guilhermeguldi , nessa linha o `id` buscado é `button-ar`, que não existe no HTML.
Nossa dev que fez o `glitch` colocou dessa forma: 
```ts
const arButton = document.getElementById('r2u')
```
A mesma div é usada para o viewer 3D em visualização desktop.

Se vc entrar [aqui](https://glitch.com/edit/#!/remix/r2u-example) dá pra ver a forma que ela implementou o `script.js`

**Comment by guilhermeguldi** [comment]
Então @FelipeR2U, esse `button-ar` é adicionado no código na linha 22, quando a tela é <= 1024:
```
arArea.innerHTML = '<div id="button-ar">Veja o Guldi na sua casa</div>'
```

**Comment by felipe-chamas** [comment]
Entendi, você tentou tirar a linha `14` e manter apenas a `15` nas opções de fallback?

**Comment by guilhermeguldi** [comment]
Na verdade não, gostaria de manter a mensagem de alerta (linha `14`) e exibir o visualizador 3D em formato 'viewer' (linha `15`).

**Comment by guilhermeguldi** [comment]
Problema resolvido!
